FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your FastAPI app, FAISS index, and IDs
COPY . .

EXPOSE 8000

CMD ["uvicorn", "faiss_db:app", "--host", "0.0.0.0", "--port", "8000"]

